### ISSUE TITLE
Error when opening a task with sub tasks while plugin is loaded

### ISSUE THREAD

**Issue by NielBuys** [stinnux/kanboard-Timetrackingeditor#19]
Error when opening a task with sub tasks while the plugin is loaded.

The plugin worked at first when I started using Kanboard, not sure at what point it stopped working.

I downloaded the newest addon zip from the Kanboard site and installed it, when I open any task with sub tasks, the screen don't render correctly (No controls are rendered so I can do no changes on a task.) and I get an error in my apache log (see error below). If I delete the plugin folder I can access my task with sub tasks as normal.

I ran the newest version of Kanboard 1.0.45. Server Ubuntu 16.04

Thanks in Advance

Error: 
`PHP Fatal error:  Uncaught Error: Call to undefined method Kanboard\\Plugin\\Timetrackingeditor\\Helper\\SubtaskHelper::getTitle() in /var/www/html/kanboard/plugins/Timetrackingeditor/Helper/SubtaskHelper.php:38\nStack trace:\n#0 /var/www/html/kanboard/plugins/Timetrackingeditor/Template/subtask/table.php(23): Kanboard\\Plugin\\Timetrackingeditor\\Helper\\SubtaskHelper->toggleStatus(Array, '4', true)\n#1 /var/www/html/kanboard/app/Core/Template.php(83): include('/var/www/html/k...')\n#2 /var/www/html/kanboard/app/Template/subtask/show.php(9): Kanboard\\Core\\Template->render('subtask/table', Array)\n#3 /var/www/html/kanboard/app/Core/Template.php(83): include('/var/www/html/k...')\n#4 /var/www/html/kanboard/app/Template/task/show.php(21): Kanboard\\Core\\Template->render('subtask/show', Array)\n#5 /var/www/html/kanboard/app/Core/Template.php(83): include('/var/www/html/k...')\n#6 /var/www/html/kanboard/app/Helper/LayoutHelper.php(205): Kanboard\\Core\\Template->render('task/show', Array)\n#7 /var/www/html/kanboard/app/Helper/LayoutHelper.php(72): Ka in /var/www/html/kanboard/plugins/Timetrackingeditor/Helper/SubtaskHelper.php on line 38 `

**Comment by NielBuys** [comment]
This error is only present when downloading plugin from https://kanboard.net/plugins. When installing Github version plugin works.
And secondly the compatibility needed to be bumped to 1.0.45 Kanboard. I forked the plugin and bumped it to 1.0.45
