### ISSUE TITLE
Task View Error for PROJECT_VIEWER

### ISSUE THREAD

**Issue by schieck0** [stinnux/kanboard-Timetrackingeditor#28]
User with project_viewer role gets this error on open a task.

Fatal error: Uncaught Error: Call to undefined method Kanboard\Helper\SubtaskHelper::getTitle() in /home/nuvoni/www/kanboard/plugins/Timetrackingeditor/Template/subtask/table.php:25 Stack trace: #0 /home/nuvoni/www/kanboard/app/Core/Template.php(83): include() #1 /home/nuvoni/www/kanboard/app/Template/subtask/show.php(7): Kanboard\Core\Template->render('subtask/table', Array) #2 /home/nuvoni/www/kanboard/app/Core/Template.php(83): include('/home/nuvoni/ww...') #3 /home/nuvoni/www/kanboard/app/Template/task/show.php(18): Kanboard\Core\Template->render('subtask/show', Array) #4 /home/nuvoni/www/kanboard/app/Core/Template.php(83): include('/home/nuvoni/ww...') #5 /home/nuvoni/www/kanboard/app/Helper/LayoutHelper.php(205): Kanboard\Core\Template->render('task/show', Array) #6 /home/nuvoni/www/kanboard/app/Helper/LayoutHelper.php(72): Kanboard\Helper\LayoutHelper->subLayout('task/layout', 'task/sidebar', 'task/show', Array) #7 /home/nuvoni/www/kanboard/app/Controller/TaskViewController.php(77): Kanboard\Helper\LayoutHelper->ta in /home/nuvoni/www/kanboard/plugins/Timetrackingeditor/Template/subtask/table.php on line 25

**Comment by schieck0** [comment]
Using Kanboard 1.2.10
